
- hosts: web

  tasks:

  #yum install scsi-target-utils -y
  - package:
      name: "scsi-target-utils"
      state: present

  #create LV
  - lvol:
      vg: vg1
      lv: 6-iscsi
      size: 87

  #create a partition in storage (don't format)

  #write in /etc/tgt/targets.conf file -
  #<target sudologin_final>
  #	  backing-store /dev/vg1/6-iscsi
  #</target>
  
  - name: "setup config file"
    copy:
      src: "/Arcus/public/tmp/iscsi/targets.conf"
      dest: "/etc/tgt/targets.conf"

  #systemctl restart tgtd
  - service:
      name: "tgtd"
      state: restarted
